@extends('layouts.adminTemplate')

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('/admin/css/app.css?v=') . time() }}">
@endsection

@section('js')
<script src="{{ asset('/js/barcode/barcode_search_isn_page.js') }}"></script>
{{-- <script src="{{ asset('js/popupNotice.js') }}"></script> --}}
<!--for notifications pop up -->
@endsection


@section('content')
<div class="container-fluid p-0">
    <div class="row mb-2 mb-xl-3 justify-content-between">
        <div class="col-auto">
            <h2 class="pb-3">{!! __('barcodeGenerator.barcode_gening') !!}</h2>
        </div>

        <div class="col-auto ml-auto text-right mt-n1 d-none d-sm-block">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-transparent p-0 mt-1 mb-0">
                    <li class="breadcrumb-item"><a href="#shouldbeDashboard">{!! __('templateWords.websiteName') !!}</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#">{!! __('templateWords.barcode_gen') !!}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{!! __('templateWords.isnBarcode') !!}
                    </li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card flex-fill w-100">
                <div class="card-body pt-3 pb-3">
                    <form class="text-center needs-validation" id="searchForm" method="post" accept-charset="utf-8"
                        novalidate autocomplete="off">
                        @csrf
                        <div class="row justify-content-center align-items-center">
                            <div class="col col-auto p-0 m-0">
                                <label for="searchIn" class="col-form-label">{!! __('barcodeGenerator.search_isn')
                                    !!}:&nbsp;&nbsp;</label>
                            </div>

                            <div class="col col-auto p-0">
                                <input type="text" name="searchIn" class="form-control p-1" id="searchIn" maxlength="12"
                                    style="width: 15ch; text-align: center;" placeholder="4010-..."
                                    pattern="[a-zA-Z0-9._%+-]{1,12}" required>
                            </div>
                        </div>
                        <div class="row justify-content-center align-items-center mt-3">
                            <button class="btn btn-primary col-auto" type="submit">{!! __('barcodeGenerator.search')
                                !!}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card flex-fill w-100">
                <div class="card-body pt-2 pb-3">
                    <div class="card-header mt-0">
                        <h3 class="card-title">{!! __('barcodeGenerator.Temporary_Storage_Zone') !!}</h3>
                        <h6 class="card-title" style="color: orangered">{!! __('barcodeGenerator.Delete_Notice') !!}
                            </h3>
                    </div>
                    <form class="text-center needs-validation" method="post" novalidate>
                        @csrf
                        <div class="table-responsive">
                            <table class="table align-items-center">
                                <tbody>
                                    <tr id="tableHead" class="table-primary align-items-center">
                                        <th class="col col-auto align-items-center px-0 m-0"><span>&nbsp;</span>
                                        </th>
                                        <th class="col col-auto align-items-center px-0 m-0"><span>{!!
                                                __('barcodeGenerator.isn') !!}</span>
                                        </th>
                                        <th class="col col-auto align-items-center px-0 m-0"><span>{!!
                                                __('barcodeGenerator.spec') !!}</span>
                                        </th>
                                        <th class="col col-auto align-items-center px-0 m-0"><span>{!!
                                                __('barcodeGenerator.print_amount') !!}</span>
                                        </th>
                                    </tr>
                                    {{-- the content here is generated by js --}}
                                </tbody>
                            </table>
                        </div>
                        <input type="hidden" name="sID" id="sID" value="{!! \Session::getId() !!}">
                        <div class="row justify-content-center align-items-center mt-3">
                            <button class="btn btn-primary col-auto" id="printBtn" type="submit">{!!
                                __('barcodeGenerator.print')
                                !!}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection